version: '3.6'

volumes:
  mysql_data:
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports: 
      - 8080:80
    volumes: 
      - .:/var/www/php
    depends_on:
      - mysql
    image: php-docker
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    image: mysql-docker
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - mysql_data:/var/lib/mysql
    env_file: 
      - ./.envs/.mysql
  phpmyadmin:
    build:
      context: .
      dockerfile: ./docker/phpmyadmin/Dockerfile
    image: phpmyadmin
    ports:
      - 8000:80
    env_file: 
      - ./.envs/.mysql
