front_home:
  path: /
  defaults: {_controller: 'App\Controllers\Frontend\HomeController::index'}
  methods: GET

front_news_details:
  path: /news/{id}
  defaults: {_controller: 'App\Controllers\Frontend\HomeController::newsDetail'}
  methods: GET

login:
  path: /login
  defaults: {_controller: 'App\Controllers\Auth\LoginController::login'}
  methods: GET

loginHandle:
  path: /login
  defaults: {_controller: 'App\Controllers\Auth\LoginController::loginHandle'}
  methods: POST

logout:
  path: /logout
  defaults: {_controller: 'App\Controllers\Auth\LoginController::logout', _middlewares: ['auth']}
  methods: POST

home:
  path: /admin
  defaults: {_controller: 'App\Controllers\HomeController::index', _middlewares: ['auth']}
  methods: GET

news:
  path: /admin/news
  defaults: {_controller: 'App\Controllers\NewsController::index', _middlewares: ['auth']}

newsCreate:
  path: /admin/news/create
  defaults: {_controller: 'App\Controllers\NewsController::create', _middlewares: ['auth']}
  methods: GET

newsCreateSave:
  path: /admin/news/create
  defaults: {_controller: 'App\Controllers\NewsController::createSave', _middlewares: ['auth']}
  methods: POST

newsDetail:
  path: /admin/news/{id}
  defaults: {_controller: 'App\Controllers\NewsController::edit', auth: true, _middlewares: ['auth']}
  methods: GET

newsEditSave:
  path: /admin/news/{id}
  defaults: {_controller: 'App\Controllers\NewsController::editSave', _middlewares: ['auth']}
  methods: POST

newsDelete:
  path: /admin/news/{id}/delete
  defaults: {_controller: 'App\Controllers\NewsController::delete', _middlewares: ['auth']}
  methods: POST