login:
  path: /login
  defaults: {_controller: 'App\Controllers\Auth\LoginController', _action: 'login'}
  methods: GET
loginHandle:
  path: /login
  defaults: {_controller: 'App\Controllers\Auth\LoginController', _action: 'loginHandle'}
  methods: POST
logout:
  path: /logout
  defaults: {_controller: 'App\Controllers\Auth\LoginController', _action: 'logout'}
  methods: POST
home:
  path: /
  defaults: {_controller: 'App\Controllers\HomeController', _action: 'index', auth: true, _middlewares: ['App\Middleware\TestMiddleware']}
  methods: GET
news:
  path: /news
  defaults: {_controller: 'App\Controllers\NewsController::index', auth: true}

newsDetail:
  path: /news/{id}
  defaults: {_controller: 'App\Controllers\NewsController::edit', auth: true}
  methods: GET
newsEditSave:
  path: /news/{id}
  defaults: {_controller: 'App\Controllers\NewsController::editSave'}